[alias]
fullstack="run --bin fullstack"
backend="run --bin backend"
frontend="run --bin frontend"

[build]
target-dir=".cargo/.build"

[target.aarch64-apple-darwin23]
linker = "clang"
rustflags = ["-Clink-arg=-fuse-ld=/opt/homebrew/bin/ld.mold"]
